# Generated by Django 5.0.6 on 2024-09-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fulllName',
            field=models.CharField(default='Default Name', max_length=50),
            preserve_default=False,
        ),
    ]
