# Generated by Django 5.0.6 on 2024-09-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_fulllname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fulllName',
            new_name='fullName',
        ),
    ]
